configversion: "1.5"
#This are the settings for the Application system:
Apply:
    Enabled: true
    Password: test
    Defaultgroup: default
    Group: Member
    Freeze: false
    Mute: false
    KickWrongPW: true
    BlockPWinChat: false
#This are the settings for the timed promotion:
Time:
    Enabled: false 
    Group: Member
    Time: 10
    CountOffline: false
#Here you can set the buyable ranks. Player with the permission 'MasterPromote.rank.buy.Example' could buy the rank for 5 coins
Ranks:
- Example,5
#Here can you set a special promote command if you do not want to use the normal one. 
#Set to none if you do not want to use this function
#For example: pex user <player> group add <group>
PromoteSyntax: none